### ISSUE TITLE
Import error despite having imported all dependencies 

### ISSUE THREAD

**Issue by Giogik09** [CalvinLoke/bad-apple#8]
Traceback (most recent call last):
  File "touhou_bad_apple_v4.0.py", line 1, in <module>
    import cv2
ImportError: No module named cv2

**Comment by CalvinLoke** [comment]
Hmm that is weird, did you do `pip install -r requirements.txt`? 

Also would help if you could include what Python version you are running.

**Comment by Giogik09** [comment]
i did and it said that i had already installed all dependencies
also i tried both using python and python3

**Comment by CalvinLoke** [comment]
Could you provide the specific version of python? If you are running Python 3.9.X, you might want to get 3.8.X, as cv2 does not currently support 3.9.X. 

Also if you have both python and python3, install the requirements for Python 3 by using 
`pip3 install -r requirements.txt` instead.

**Comment by Giogik09** [comment]
ok, i'll try

**Comment by Giogik09** [comment]
yooo it worked, thanks man

**Comment by Giogik09** [comment]
actually i'm having another problem now

**Comment by Giogik09** [comment]
Your option: 1
Original mp3 (0), Midi (1)
Enter 0 or 1: 1
Beginning ASCII generation...
Progress: [#######################  ] 99% Frame 6571 of 6572 frames
ASCII generation completed! ASCII generation time: 33.6171236038208Traceback (most recent call last):
  File "/home/kali/bad-apple/touhou_bad_apple_v4.0.py", line 204, in <module>
    main()
  File "/home/kali/bad-apple/touhou_bad_apple_v4.0.py", line 190, in main
    play_audio(path_to_file)
  File "/home/kali/bad-apple/touhou_bad_apple_v4.0.py", line 24, in play_audio
    pygame.mixer.music.load(path)
pygame.error: Couldn't open /etc/timidity/freepats.cfg

do i have to edit something in the file?

**Comment by Giogik09** [comment]
it looks like it can't recognize the audio format for some reason

**Comment by CalvinLoke** [comment]
Hi there, really sorry for replying back so late. As option 1 plays back the midi file, it requires the use of a midi player. Judging by your directory, your host system seems to be Linux-based, which I presume does not have a built-in midi player. You might want to search up on that. 

Cheers
